import {
  Code2,
  Database,
  Cloud,
  BrainCircuit,
  Server,
  Blocks,
  Search,
  MessagesSquare,
} from "lucide-react";
import {
  FaAws,
  FaCss3Alt,
  FaDatabase,
  FaDocker,
  FaGit,
  FaHtml5,
  FaJs,
  FaNodeJs,
  FaPython,
  FaReact,
  FaServer,
} from "react-icons/fa";
import { TbApi, TbBrandRedux } from "react-icons/tb";
import {
  SiAmazonaws,
  SiAwslambda,
  SiDjango,
  SiExpress,
  SiFastapi,
  SiGithubactions,
  SiGraphql,
  SiMongodb,
  SiMui,
  SiMysql,
  SiNextdotjs,
  SiOpenai,
  SiPostgresql,
  SiReactquery,
  SiRedis,
  SiSwagger,
  SiTailwindcss,
  SiTypescript,
  SiVercel,
} from "react-icons/si";

export const stackCategories = [
  {
    id: "frontend",
    label: "Frontend",
    title: "Frontend systems",
    Icon: Code2,
    copy: "Accessible, SSR/SSG-optimized React and Next.js interfaces with reusable design systems, Tailwind CSS, and crisp interaction layers tuned for performance and responsiveness.",
  },
  {
    id: "backend",
    label: "Backend & Databases",
    title: "Full-stack APIs",
    Icon: Server,
    copy: "Production grade REST services with Node.js, Express, and FastAPI featuring JWT auth, RBAC, rate-limiting, and resilient integrations serving 10K+ daily requests at 99.9% uptime.",
  },
  {
    id: "cloud",
    label: "Cloud & DevOps",
    title: "Cloud delivery",
    Icon: Cloud,
    copy: "AWS native deployment across S3, EC2, serverless functions, and containers with CI/CD pipelines via GitHub Actions and Docker that cut release cycles by 40%.",
  },
  {
    id: "ai",
    label: "AI Integration",
    title: "AI Integration",
    Icon: BrainCircuit,
    copy: "LLM powered apps, RAG pipelines, vector search, and agentic workflows woven directly into web products for real user impact.",
  },
];

export const skillRows = [
  {
    category: "frontend",
    label: "Frontend",
    direction: "left",
    Icon: Code2,
    skills: [
      { Icon: FaHtml5, name: "HTML5", color: "#f97316" },
      { Icon: FaCss3Alt, name: "CSS3", color: "#3b82f6" },
      { Icon: FaJs, name: "JavaScript", color: "#facc15" },
      { Icon: SiTypescript, name: "TypeScript", color: "#60a5fa" },
      { Icon: FaReact, name: "React.js", color: "#22d3ee" },
      { Icon: SiNextdotjs, name: "Next.js", color: "#e5e7eb" },
      { Icon: TbBrandRedux, name: "Redux Toolkit", color: "#a78bfa" },
      { Icon: SiReactquery, name: "TanStack Query", color: "#f87171" },
      { Icon: SiTailwindcss, name: "Tailwind CSS", color: "#2dd4bf" },
      { Icon: SiMui, name: "Material UI", color: "#3b82f6" },
      { Icon: TbApi, name: "WebSockets", color: "#4ade80" },
    ],
  },
  {
    category: "backend",
    label: "Backend & Databases",
    direction: "right",
    Icon: Database,
    skills: [
      { Icon: FaNodeJs, name: "Node.js", color: "#22c55e" },
      { Icon: SiExpress, name: "Express.js", color: "#d1d5db" },
      { Icon: SiFastapi, name: "FastAPI", color: "#14b8a6" },
      { Icon: SiDjango, name: "Django", color: "#16a34a" },
      { Icon: FaPython, name: "Python", color: "#facc15" },
      { Icon: SiGraphql, name: "GraphQL", color: "#ec4899" },
      { Icon: TbApi, name: "REST APIs", color: "#4ade80" },
      { Icon: SiPostgresql, name: "PostgreSQL", color: "#60a5fa" },
      { Icon: SiMongodb, name: "MongoDB", color: "#22c55e" },
      { Icon: SiMysql, name: "MySQL", color: "#eab308" },
      { Icon: SiRedis, name: "Redis", color: "#ef4444" },
      { Icon: FaDatabase, name: "SQL Server", color: "#93c5fd" },
    ],
  },
  {
    category: "cloud",
    label: "Cloud & DevOps",
    direction: "left",
    Icon: Cloud,
    skills: [
      { Icon: FaAws, name: "AWS", color: "#fbbf24" },
      { Icon: SiAmazonaws, name: "Amazon S3", color: "#f59e0b" },
      { Icon: SiAwslambda, name: "AWS Lambda", color: "#fb923c" },
      { Icon: FaDocker, name: "Docker", color: "#60a5fa" },
      { Icon: SiGithubactions, name: "GitHub Actions", color: "#d1d5db" },
      { Icon: FaGit, name: "Git", color: "#f97316" },
      { Icon: SiVercel, name: "Vercel", color: "#f3f4f6" },
      { Icon: SiSwagger, name: "Swagger", color: "#4ade80" },
    ],
  },
  {
    category: "ai",
    label: "AI Integration",
    direction: "right",
    Icon: BrainCircuit,
    skills: [
      { Icon: SiOpenai, name: "OpenAI APIs", color: "#22d3ee" },
      { Icon: Blocks, name: "LLM Orchestration", color: "#4ade80" },
      { Icon: MessagesSquare, name: "AI Assistants", color: "#c084fc" },
      { Icon: Search, name: "RAG Pipelines", color: "#f472b6" },
      { Icon: Search, name: "Vector Search", color: "#2dd4bf" },
      { Icon: BrainCircuit, name: "Model Integration", color: "#93c5fd" },
      { Icon: Blocks, name: "Agentic Workflows", color: "#a78bfa" },
    ],
  },
];
